name: 'Jeremiah Hundley '
favicon: null
layout_spectrum: 0
typography_spectrum: 0.5656134
title: Confessions of a Storyteller
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050a04'
    - '#485150'
    - '#c0d0d7'
    - '#f7ad78'
    - '#8f9da0'
  brandStrength: 0
  lightness: 0.6875
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
