name: 'Jeremiah Hundley '
favicon: null
layout_spectrum: 0
typography_spectrum: 0.5656134
title: Confessions of a Storyteller
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.009280022
  lightness: 0.3077336
  saturation: 0.434479
  rhythmicContrast: 0.4108485
purpose: []
