layout_spectrum: 0
typography_spectrum: 0.5656134
color:
  saturation: 0.434479
  brandStrength: 0.009280022
  lightness: 0.3077336
  rhythmicContrast: 0.4108485
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
name: 'Jeremiah Hundley '
